[package]
name = "ui"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
serde.workspace = true
serde_json.workspace = true
models = { path = "../models" }
store = { path = "../store" }
